const Flashcard = require('../models/Flashcard');
const Document = require('../models/Document');
const Usage = require('../models/Usage');
const { callClaude } = require('../services/claudeService');
const { extractTextFromFile } = require('../services/documentService');

// Generate flashcards
exports.generateFlashcards = async (req, res, next) => {
  try {
    const { documentId, numberOfCards = 20 } = req.body;
    let { setTitle } = req.body;
    const userId = req.user._id;

    const document = await Document.findById(documentId);
    if (!document || document.userId.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    // Auto-generate setTitle if not provided
    if (!setTitle) {
      setTitle = `${document.title} - Flashcards`;
    }

    // Call Claude to generate flashcards
    const prompt = `Generate exactly ${numberOfCards} concise flashcards from this document.
Each card must have:
- "front": a short question or term (max 80 characters)
- "back": a clear, direct answer in 1–2 short sentences (max 35 words).

Avoid long paragraphs. Focus only on the key idea needed to answer the question.

Return ONLY a JSON array of objects with "front" and "back" keys. Do not include any extra text.

Document:
${document.textContent}`;

    const claudeMessages = [
      {
        role: 'user',
        content: prompt,
      },
    ];

    const claudeResponse = await callClaude(claudeMessages, 'flashcards', 2048);

    // Parse flashcards from Claude response
    let flashcardsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      flashcardsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);
    } catch (parseError) {
      flashcardsData = [
        {
          front: 'Sample Question',
          back: 'Sample Answer - AI failed to parse full response',
        },
      ];
    }

    // Create flashcard set
    const flashcard = new Flashcard({
      userId,
      documentId,
      setTitle,
      cards: flashcardsData,
      totalCards: flashcardsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
    });

    await flashcard.save();

    // Update usage
    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;

      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'flashcards');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({
          featureName: 'flashcards',
          inputTokens: claudeResponse.inputTokens,
          outputTokens: claudeResponse.outputTokens,
          count: 1,
        });
      }

      await usage.save();
    }

    res.status(201).json({
      success: true,
      flashcard: {
        id: flashcard._id,
        setTitle: flashcard.setTitle,
        totalCards: flashcard.totalCards,
      },
      tokensUsed: {
        input: claudeResponse.inputTokens,
        output: claudeResponse.outputTokens,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Get user's flashcard sets
exports.getUserFlashcards = async (req, res, next) => {
  try {
    const userId = req.user._id;
    const flashcards = await Flashcard.find({ userId }).select(
      'setTitle totalCards documentId createdAt'
    );

    res.status(200).json({
      success: true,
      flashcards,
    });
  } catch (error) {
    next(error);
  }
};

// Get flashcard set details
exports.getFlashcardSet = async (req, res, next) => {
  try {
    const { flashcardId } = req.params;
    const flashcard = await Flashcard.findById(flashcardId);

    if (!flashcard || flashcard.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    res.status(200).json({
      success: true,
      flashcard,
    });
  } catch (error) {
    next(error);
  }
};

// Update flashcard progress
exports.updateFlashcardProgress = async (req, res, next) => {
  try {
    const { flashcardId, cardIndex, difficulty } = req.body;
    const flashcard = await Flashcard.findById(flashcardId);

    if (!flashcard || flashcard.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    if (flashcard.cards[cardIndex]) {
      flashcard.cards[cardIndex].difficulty = difficulty || 'medium';
      flashcard.cards[cardIndex].timesReviewed += 1;
      flashcard.cards[cardIndex].lastReviewedAt = new Date();
    }

    await flashcard.save();

    res.status(200).json({
      success: true,
      message: 'Card progress updated',
    });
  } catch (error) {
    next(error);
  }
};

// Generate flashcards from topic/text (no document required)
exports.generateFlashcardsFromText = async (req, res, next) => {
  try {
    const { topic, numberOfCards = 10, difficulty = 'intermediate', setTitle } = req.body;
    const userId = req.user._id;

    if (!topic) {
      return res.status(400).json({ success: false, message: 'topic is required' });
    }

    const prompt = `Generate exactly ${numberOfCards} concise flashcards about "${topic}".
Difficulty level: ${difficulty}

For each card:
- "front": a short question or term (max 80 characters)
- "back": a clear answer in 1–2 short sentences (max 35 words).

Avoid long paragraphs. Focus only on the essential idea.

Return ONLY a valid JSON array with this structure (no extra text before or after):
[
  { "front": "Question or term here?", "back": "Answer or definition here" }
]`;

    const claudeMessages = [{ role: 'user', content: prompt }];
    const claudeResponse = await callClaude(claudeMessages, 'flashcards', 2048);

    let flashcardsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      flashcardsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);
      if (!Array.isArray(flashcardsData)) throw new Error('Not an array');
      flashcardsData = flashcardsData.slice(0, numberOfCards);
    } catch (parseError) {
      return res.status(400).json({ success: false, message: 'Failed to generate flashcards. Please try again.' });
    }

    const title = setTitle || `${topic} Flashcards (${difficulty})`;
    const flashcard = new Flashcard({
      userId,
      setTitle: title,
      cards: flashcardsData,
      totalCards: flashcardsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
    });
    await flashcard.save();

    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;
      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'flashcards');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({ featureName: 'flashcards', inputTokens: claudeResponse.inputTokens, outputTokens: claudeResponse.outputTokens, count: 1 });
      }
      await usage.save();
    }

    res.status(201).json({
      success: true,
      flashcard: {
        _id: flashcard._id,
        setTitle: flashcard.setTitle,
        totalCards: flashcard.totalCards,
        cards: flashcard.cards,
        createdAt: flashcard.createdAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Generate flashcards from uploaded file
exports.generateFlashcardsFromFile = async (req, res, next) => {
  try {
    const { numberOfCards = 10, difficulty = 'intermediate' } = req.body;
    const userId = req.user._id;
    const file = req.file;

    if (!file) {
      return res.status(400).json({ success: false, message: 'Please upload a file (PDF, DOCX, DOC, or PPTX)' });
    }

    let fileContent = '';
    try {
      const extracted = await extractTextFromFile(file);
      fileContent = extracted.text;
    } catch (extractError) {
      return res.status(400).json({ success: false, message: `Failed to extract text: ${extractError.message}` });
    }

    if (!fileContent || fileContent.trim().length < 50) {
      return res.status(400).json({ success: false, message: 'File has insufficient content to generate flashcards' });
    }

    const prompt = `Generate exactly ${numberOfCards} concise flashcards from this content. Difficulty: ${difficulty}.

Content:
"""
${fileContent}
"""

For each card:
- "front": a short question or term (max 80 characters)
- "back": a clear answer in 1–2 short sentences (max 35 words).

Avoid long paragraphs. Focus only on the essential idea for the answer.

Return ONLY a valid JSON array with this exact structure. DO NOT include any text before or after the JSON:
[
  { "front": "Question or term here?", "back": "Answer or definition here" }
]`;

    const claudeMessages = [{ role: 'user', content: prompt }];
    const claudeResponse = await callClaude(claudeMessages, 'flashcards_from_file', 2048);

    let flashcardsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      flashcardsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);
      if (!Array.isArray(flashcardsData)) throw new Error('Not an array');
      flashcardsData = flashcardsData.slice(0, numberOfCards);
    } catch (parseError) {
      return res.status(400).json({ success: false, message: 'Failed to generate flashcards from file. Please try again.' });
    }

    const title = `${file.originalname} Flashcards`;
    const flashcard = new Flashcard({
      userId,
      setTitle: title,
      cards: flashcardsData,
      totalCards: flashcardsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
    });
    await flashcard.save();

    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;
      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'flashcards');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({ featureName: 'flashcards', inputTokens: claudeResponse.inputTokens, outputTokens: claudeResponse.outputTokens, count: 1 });
      }
      await usage.save();
    }

    res.status(201).json({
      success: true,
      flashcard: {
        _id: flashcard._id,
        setTitle: flashcard.setTitle,
        totalCards: flashcard.totalCards,
        cards: flashcard.cards,
        createdAt: flashcard.createdAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

exports.deleteFlashcardSet = async (req, res, next) => {
  try {
    const { flashcardId } = req.params;
    const flashcard = await Flashcard.findById(flashcardId);
    if (!flashcard || flashcard.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }
    await Flashcard.findByIdAndDelete(flashcardId);
    res.status(200).json({ success: true, message: 'Flashcard set deleted' });
  } catch (error) {
    next(error);
  }
};
