const Quiz = require('../models/Quiz');
const Document = require('../models/Document');
const Usage = require('../models/Usage');
const { callClaude } = require('../services/claudeService');
const { extractTextFromFile } = require('../services/documentService');
const { isValidObjectId, MIN_GENERATED, MAX_GENERATED } = require('../validators/schemas');

// Shuffle options and update correctAnswer index so the correct answer
// is not always in the same position (Claude tends to put it at index 0).
function shuffleOptions(questions) {
  return questions.map(q => {
    // Normalize correctAnswer to an index first
    let correctIdx = 0;
    const ca = q.correctAnswer;
    if (typeof ca === 'number') {
      correctIdx = ca;
    } else if (typeof ca === 'string') {
      const upper = ca.trim().toUpperCase();
      if (['A', 'B', 'C', 'D'].includes(upper)) {
        correctIdx = upper.charCodeAt(0) - 65;
      } else {
        const found = q.options.findIndex(
          o => o.trim().toLowerCase() === ca.trim().toLowerCase()
        );
        correctIdx = found >= 0 ? found : 0;
      }
    }

    // Fisher-Yates shuffle on a copy of options
    const opts = [...q.options];
    for (let i = opts.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [opts[i], opts[j]] = [opts[j], opts[i]];
    }

    // Find where the correct answer ended up after shuffle
    const newCorrectIdx = opts.indexOf(q.options[correctIdx]);

    return { ...q, options: opts, correctAnswer: newCorrectIdx };
  });
}

// Generate quiz
exports.generateQuiz = async (req, res, next) => {
  try {
    const { documentId, quizTitle, numberOfQuestions: _rawQ = 10 } = req.body;
    const userId = req.user._id;
    const numberOfQuestions = Math.min(Math.max(parseInt(_rawQ, 10) || 10, MIN_GENERATED), MAX_GENERATED);

    if (!documentId || !isValidObjectId(documentId)) {
      return res.status(400).json({ message: 'Valid documentId is required' });
    }

    const document = await Document.findById(documentId);
    if (!document || document.userId.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    // Call Claude to generate quiz
    const prompt = `Generate exactly ${numberOfQuestions} multiple choice questions from this document. Return JSON format with array of objects containing "question", "options" (array of 4 strings), "correctAnswer" (the 0-based index of the correct option — vary this across questions, do NOT always use 0), and "explanation" keys. Only return valid JSON array.\n\nDocument:\n${document.textContent}`;

    const claudeMessages = [
      {
        role: 'user',
        content: prompt,
      },
    ];

    const claudeResponse = await callClaude(claudeMessages, 'quiz', 2048);

    // Parse quiz from Claude response
    let questionsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      questionsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);
    } catch (parseError) {
      questionsData = [
        {
          question: 'Sample Question?',
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
          correctAnswer: 0,
          explanation: 'AI parsing failed',
        },
      ];
    }
    questionsData = shuffleOptions(questionsData);

    // Create quiz
    const quiz = new Quiz({
      userId,
      documentId,
      quizTitle,
      questions: questionsData,
      totalQuestions: questionsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
    });

    await quiz.save();

    // Update usage
    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;

      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'quiz');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({
          featureName: 'quiz',
          inputTokens: claudeResponse.inputTokens,
          outputTokens: claudeResponse.outputTokens,
          count: 1,
        });
      }

      await usage.save();
    }

    res.status(201).json({
      success: true,
      quiz: {
        id: quiz._id,
        quizTitle: quiz.quizTitle,
        totalQuestions: quiz.totalQuestions,
        questions: questionsData,
      },
      tokensUsed: {
        input: claudeResponse.inputTokens,
        output: claudeResponse.outputTokens,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Generate quiz from topic/text (no document required)
exports.generateQuizFromText = async (req, res, next) => {
  try {
    console.log('Received request to generate quiz from text with body:', req.body);
  const { topic: topic0, text, numberOfQuestions = 10, difficulty = 'intermediate', quizTitle } = req.body;
const topic = topic0 || text;
    const userId = req.user._id;

    if (!topic) {
      return res.status(400).json({
        success: false,
        message: 'topic is required',
      });
    }

    if (numberOfQuestions < 1 || numberOfQuestions > 50) {
      return res.status(400).json({
        success: false,
        message: 'numberOfQuestions must be between 1 and 50',
      });
    }

    const validDifficulties = ['easy', 'intermediate', 'hard'];
    if (!validDifficulties.includes(difficulty)) {
      return res.status(400).json({
        success: false,
        message: 'difficulty must be easy, intermediate, or hard',
      });
    }

    // Create prompt for quiz generation
    const prompt = `Generate exactly ${numberOfQuestions} multiple choice quiz questions about "${topic}".

Difficulty level: ${difficulty}

Rules:
- Create questions that sound natural and clear
- Each question should have 4 options (A, B, C, D)
- IMPORTANT: Randomize which option is correct — spread correctAnswer values across 0, 1, 2, and 3. Do NOT use 0 for every question.
- Include good explanations for why the correct answer is right
- For ${difficulty} difficulty, adjust complexity accordingly

Return ONLY valid JSON array with this exact structure. DO NOT include any text before or after the JSON:
[
  {
    "question": "Question text here?",
    "options": ["Wrong answer", "Correct answer", "Wrong answer", "Wrong answer"],
    "correctAnswer": 1,
    "explanation": "Why this is the correct answer"
  }
]`;

    const claudeMessages = [
      {
        role: 'user',
        content: prompt,
      },
    ];

    const claudeResponse = await callClaude(claudeMessages, 'quiz_from_text', 2048);

    // Parse quiz from Claude response
    let questionsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      questionsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);
      
      // Validate questions structure
      if (!Array.isArray(questionsData)) {
        throw new Error('Response is not an array');
      }
      
      questionsData = questionsData.slice(0, numberOfQuestions);
      questionsData = shuffleOptions(questionsData);
    } catch (parseError) {
      console.error('Parse error:', parseError.message);
      return res.status(400).json({
        success: false,
        message: 'Failed to generate valid quiz. Please try again.',
        error: parseError.message,
      });
    }

    // Create quiz document
    const title = quizTitle || `${topic} Quiz (${difficulty})`;
    const quiz = new Quiz({
      userId,
      quizTitle: title,
      questions: questionsData,
      totalQuestions: questionsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
      source: 'text_generation',
    });

    await quiz.save();

    // Update usage tracking
    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;

      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'quiz');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({
          featureName: 'quiz',
          inputTokens: claudeResponse.inputTokens,
          outputTokens: claudeResponse.outputTokens,
          count: 1,
        });
      }

      await usage.save();
    }

    res.status(201).json({
      success: true,
      quiz: {
        id: quiz._id,
        quizTitle: quiz.quizTitle,
        topic,
        difficulty,
        totalQuestions: quiz.totalQuestions,
        questions: questionsData,
      },
      tokensUsed: {
        input: claudeResponse.inputTokens,
        output: claudeResponse.outputTokens,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Generate quiz directly from uploaded file
exports.generateQuizFromFile = async (req, res, next) => {
  try {
    const { numberOfQuestions = 10, difficulty = 'intermediate', quizTitle } = req.body;
    const userId = req.user._id;
    const file = req.file;

    if (!file) {
      return res.status(400).json({
        success: false,
        message: 'Please upload a file (PDF, DOCX, DOC, or PPTX)',
      });
    }

    if (numberOfQuestions < 1 || numberOfQuestions > 50) {
      return res.status(400).json({
        success: false,
        message: 'numberOfQuestions must be between 1 and 50',
      });
    }

    const validDifficulties = ['easy', 'intermediate', 'hard'];
    if (!validDifficulties.includes(difficulty)) {
      return res.status(400).json({
        success: false,
        message: 'difficulty must be easy, intermediate, or hard',
      });
    }

    // Extract text from uploaded file
    let fileContent = '';
    try {
      const extracted = await extractTextFromFile(file);
      fileContent = extracted.text;
    } catch (extractError) {
      return res.status(400).json({
        success: false,
        message: `Failed to extract text from file: ${extractError.message}`,
      });
    }

    if (!fileContent || fileContent.trim().length < 50) {
      return res.status(400).json({
        success: false,
        message: 'File has insufficient content to generate quiz',
      });
    }

    // Create prompt for quiz generation from file
    const prompt = `Generate exactly ${numberOfQuestions} multiple choice quiz questions based on this content:

Content:
"""
${fileContent}
"""

Difficulty level: ${difficulty}

Rules:
- Create questions that sound natural and clear
- Each question should have 4 options (A, B, C, D)
- IMPORTANT: Randomize which option is correct — spread correctAnswer values across 0, 1, 2, and 3. Do NOT use 0 for every question.
- Include good explanations for why the correct answer is right
- For ${difficulty} difficulty, adjust complexity accordingly
- Questions should be based only on the provided content

Return ONLY valid JSON array with this exact structure. DO NOT include any text before or after the JSON:
[
  {
    "question": "Question text here?",
    "options": ["Wrong answer", "Correct answer", "Wrong answer", "Wrong answer"],
    "correctAnswer": 1,
    "explanation": "Why this is the correct answer"
  }
]`;

    const claudeMessages = [
      {
        role: 'user',
        content: prompt,
      },
    ];

    const claudeResponse = await callClaude(claudeMessages, 'quiz_from_file', 2048);

    // Parse quiz from Claude response
    let questionsData = [];
    try {
      const jsonMatch = claudeResponse.content.match(/\[[\s\S]*\]/);
      questionsData = JSON.parse(jsonMatch ? jsonMatch[0] : claudeResponse.content);

      if (!Array.isArray(questionsData)) {
        throw new Error('Response is not an array');
      }

      questionsData = questionsData.slice(0, numberOfQuestions);
      questionsData = shuffleOptions(questionsData);
    } catch (parseError) {
      console.error('Parse error:', parseError.message);
      return res.status(400).json({
        success: false,
        message: 'Failed to generate valid quiz from file. Please try again.',
        error: parseError.message,
      });
    }

    // Create quiz document
    const title = quizTitle || `${file.originalname} Quiz (${difficulty})`;
    const quiz = new Quiz({
      userId,
      quizTitle: title,
      questions: questionsData,
      totalQuestions: questionsData.length,
      autoGeneratedTokens: claudeResponse.outputTokens,
      source: 'file_upload',
      fileName: file.originalname,
    });

    await quiz.save();

    // Update usage tracking
    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.inputTokens += claudeResponse.inputTokens;
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;

      const featureUsage = usage.usageBreakdown.find((u) => u.featureName === 'quiz');
      if (featureUsage) {
        featureUsage.inputTokens += claudeResponse.inputTokens;
        featureUsage.outputTokens += claudeResponse.outputTokens;
        featureUsage.count += 1;
      } else {
        usage.usageBreakdown.push({
          featureName: 'quiz',
          inputTokens: claudeResponse.inputTokens,
          outputTokens: claudeResponse.outputTokens,
          count: 1,
        });
      }

      await usage.save();
    }

    res.status(201).json({
      success: true,
      quiz: {
        id: quiz._id,
        quizTitle: quiz.quizTitle,
        fileName: file.originalname,
        difficulty,
        totalQuestions: quiz.totalQuestions,
        questions: questionsData,
      },
      tokensUsed: {
        input: claudeResponse.inputTokens,
        output: claudeResponse.outputTokens,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Get user's quizzes
exports.getUserQuizzes = async (req, res, next) => {
  try {
    const userId = req.user._id;
    const quizzes = await Quiz.find({ userId }).select(
      'quizTitle totalQuestions documentId createdAt'
    );

    res.status(200).json({
      success: true,
      quizzes,
    });
  } catch (error) {
    next(error);
  }
};

// Get quiz details
exports.getQuizDetails = async (req, res, next) => {
  try {
    const { quizId } = req.params;
    const quiz = await Quiz.findById(quizId);

    if (!quiz || quiz.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    res.status(200).json({
      success: true,
      quiz,
    });
  } catch (error) {
    next(error);
  }
};

// Submit quiz attempt
exports.submitQuizAttempt = async (req, res, next) => {
  try {
    const { quizId } = req.params;
    const { answers } = req.body; // Array of selected answers
    const userId = req.user._id;

    // Validate answers array
    if (!answers || !Array.isArray(answers)) {
      return res.status(400).json({
        message: 'Invalid request. Provide answers array: { "answers": ["answerA", "answerB", ...] }'
      });
    }

    const quiz = await Quiz.findById(quizId);
    if (!quiz || quiz.userId.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }

    // Calculate score
    let score = 0;
    const feedback = [];

    quiz.questions.forEach((question, index) => {
      const isCorrect = answers[index] === question.correctAnswer;
      if (isCorrect) score += 1;

      feedback.push({
        questionIndex: index,
        isCorrect,
        explanation: question.explanation,
      });
    });

    // Get AI feedback on attempt
    const feedbackPrompt = `Review this quiz attempt and provide encouraging feedback. Score: ${score}/${quiz.questions.length} (${Math.round((score / quiz.questions.length) * 100)}%)`;

    const claudeMessages = [
      {
        role: 'user',
        content: feedbackPrompt,
      },
    ];

    const claudeResponse = await callClaude(claudeMessages, 'qa', 512);

    // Save attempt
    const attempt = {
      userId,
      score,
      totalMarks: quiz.questions.length,
      answers,
      feedback: claudeResponse.content,
      attemptedAt: new Date(),
    };

    quiz.attempts.push(attempt);
    await quiz.save();

    // Update usage
    const usage = await Usage.findOne({ userId });
    if (usage) {
      usage.outputTokens += claudeResponse.outputTokens;
      usage.totalTokens = usage.inputTokens + usage.outputTokens;
      await usage.save();
    }

    res.status(200).json({
      success: true,
      result: {
        score,
        totalMarks: quiz.questions.length,
        percentage: Math.round((score / quiz.questions.length) * 100),
        feedback: claudeResponse.content,
        details: feedback,
      },
    });
  } catch (error) {
    next(error);
  }
};

exports.deleteQuiz = async (req, res, next) => {
  try {
    const { quizId } = req.params;
    const quiz = await Quiz.findById(quizId);
    if (!quiz || quiz.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Unauthorized access' });
    }
    await Quiz.findByIdAndDelete(quizId);
    res.status(200).json({ success: true, message: 'Quiz deleted' });
  } catch (error) {
    next(error);
  }
};
