const mongoose = require('mongoose');

const flashcardSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    documentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Document',
    },
    setTitle: {
      type: String,
      required: true,
    },
    cards: [
      {
        front: {
          type: String,
          required: true,
        },
        back: {
          type: String,
          required: true,
        },
        difficulty: {
          type: String,
          enum: ['easy', 'medium', 'hard'],
          default: 'medium',
        },
        timesReviewed: {
          type: Number,
          default: 0,
        },
        lastReviewedAt: Date,
      },
    ],
    totalCards: {
      type: Number,
      default: 0,
    },
    autoGeneratedTokens: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Flashcard', flashcardSchema);
