const mongoose = require('mongoose');

const quizSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    documentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Document',
      required: false,  // Optional - only when generated from document
    },
    quizTitle: {
      type: String,
      required: true,
    },
    questions: [
      {
        question: String,
        options: [String],
        correctAnswer: String,
        explanation: String,
      },
    ],
    totalQuestions: {
      type: Number,
      default: 0,
    },
    attempts: [
      {
        userId: mongoose.Schema.Types.ObjectId,
        score: Number,
        totalMarks: Number,
        answers: [String],
        feedback: String, // AI-generated feedback
        attemptedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
    autoGeneratedTokens: {
      type: Number,
      default: 0,
    },
    source: {
      type: String,
      enum: ['document', 'text_generation', 'file_upload'],
      default: 'document',
    },
    fileName: {
      type: String,
      required: false,  // Only for file uploads
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Quiz', quizSchema);
